#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Code Generate.py - 自动生成 C/C++ 预处理器可变参数计数宏

工作原理:
1. 生成形如 REFLECT__PP_FOREACH_N(f, _1, _2, ..., _N) 的宏，展开为 f(_1) f(_2) ... f(_N)。
2. 生成 REFLECT__PP_NARGS_IMPL(_1, _2, ..., _N, N, ...) N 宏，用于提取参数个数。
3. 生成 REFLECT__PP_NARGS(...) 宏，它通过向 NARGS_IMPL 传递递减序列来计算实际参数数量。
4. 这些宏通常用于实现可变参数宏的遍历和计数，是 C/C++ 预处理器元编程的常见模式。

本工具可以:
- 将生成的宏块插入或替换到指定头文件中（基于 BEGIN/END 标记）。
- 在没有输入文件时自动创建临时输出文件。
- 支持递归查找输入文件（当仅提供文件名时）。
- 查找策略:从脚本所在目录向上寻找名为 "PythonTools"（可配置）的目录，然后在其父目录下递归搜索。
"""

import os
import re
import sys
import argparse
from pathlib import Path

# ======================= 默认配置 =======================
DEFAULT_MAX = 128                       # 最大支持参数个数
DEFAULT_FOREACH_PREFIX = "MACRO_ARGS_NUM_FOREACH"
DEFAULT_NARGS_PREFIX = "MACRO_ARGS_NUM"
DEFAULT_NARGS_IMPL_PREFIX = "MACRO_ARGS_NUM_IMPL"
DEFAULT_TOOLS_DIR_NAME = "PythonTools"   # 向上查找的目录名
DEFAULT_DEPTH = 5                        # 递归搜索深度
OUTPUT_DIR_NAME = "output"               # 临时输出文件夹
TEMP_FILE_PREFIX = "__Temp_Output_"      # 临时文件前缀
TEMP_FILE_SUFFIX = ".h"                  # 临时文件后缀

# 标记行，用于识别自动生成的代码块
BEGIN_MARKER = "// BEGIN GENERATED BY Code Generate.py"
END_MARKER = "// END GENERATED BY Code Generate.py"


# ======================= 宏生成函数 =======================
def generate_foreach_macros(prefix, max_n):
    """生成 REFLECT__PP_FOREACH_1 到 REFLECT__PP_FOREACH_MAX_N 的宏定义"""
    lines = []
    for n in range(1, max_n + 1):
        # 参数列表:_1, _2, ..., _n
        params = [f"_{i}" for i in range(1, n + 1)]
        # 宏形参列表:f, _1, _2, ..., _n
        macro_params = ["f"] + params
        macro_params_str = ", ".join(macro_params)
        # 宏体:f(_1) f(_2) ... f(_n)
        body = " ".join(f"f({p})" for p in params)
        lines.append(f"#define {prefix}_{n}({macro_params_str}) {body}")
    return "\n".join(lines)


def generate_nargs_impl_macro(prefix, max_n):
    """
    生成形如 REFLECT__PP_NARGS_IMPL(_1, _2, ..., _N, N, ...) N 的宏
    其中 N = max_n，参数个数最多为 max_n
    """
    params = [f"_{i}" for i in range(1, max_n + 1)]
    params_str = ", ".join(params + ["N", "..."])
    return f"#define {prefix}({params_str}) N"


def generate_nargs_macro(prefix, impl_prefix, max_n):
    """
    生成 REFLECT__PP_NARGS(...) 宏，利用递减序列和 NARGS_IMPL 计算参数个数。
    例如:REFLECT__PP_NARGS(a, b, c) 展开为 REFLECT__PP_NARGS_IMPL(a, b, c, 32,31,...,1)
    由于 NARGS_IMPL 取第 (max_n+1) 个参数（即 N），所以当给定 K 个参数时，
    第 (K+1) 个参数正好是递减序列中的 K，因此得到参数数量。
    """
    decreasing = ", ".join(str(i) for i in range(max_n, 0, -1))
    return f"#define {prefix}(...) {impl_prefix}(__VA_ARGS__, {decreasing})"


def generate_all_macros(foreach_prefix, nargs_prefix, nargs_impl_prefix, max_n):
    """组合所有宏，并用 BEGIN/END 标记包裹"""
    foreach_part = generate_foreach_macros(foreach_prefix, max_n)
    nargs_impl_part = generate_nargs_impl_macro(nargs_impl_prefix, max_n)
    nargs_part = generate_nargs_macro(nargs_prefix, nargs_impl_prefix, max_n)

    content = f"{BEGIN_MARKER}\n"
    content += foreach_part + "\n"
    content += nargs_impl_part + "\n"
    content += nargs_part + "\n"
    content += f"{END_MARKER}\n"
    return content


# ======================= 文件查找与操作 =======================
def find_tools_parent_dir(start_dir, tools_dir_name):
    """
    从 start_dir 开始向上查找名为 tools_dir_name 的目录，
    找到后返回该目录的父目录（即搜索根目录）。
    如果找不到，返回 start_dir 的父目录（回退行为）。
    """
    current = Path(start_dir).resolve()
    while current != current.parent:
        if current.name == tools_dir_name:
            # 找到目标目录，返回其父目录
            return current.parent
        current = current.parent
    # 未找到，返回原 start_dir 的父目录
    return Path(start_dir).parent


def find_file_recursively(filename, root_dir, max_depth):
    """
    在 root_dir 下递归查找 filename，深度不超过 max_depth。
    返回第一个匹配的绝对路径，未找到返回 None。
    """
    root_dir = Path(root_dir).resolve()
    if not root_dir.exists():
        return None

    # 使用广度优先遍历，控制深度
    for root, dirs, files in os.walk(root_dir):
        rel_path = Path(root).relative_to(root_dir)
        depth = len(rel_path.parts) if rel_path != Path(".") else 0
        if depth > max_depth:
            continue
        if filename in files:
            return Path(root) / filename
    return None


def replace_or_append_content(file_path, new_content):
    """
    在文件中查找 BEGIN_MARKER 和 END_MARKER 对:
    - 如果找到完整的一对，则替换之间的内容。
    - 否则将新内容追加到文件末尾。
    """
    file_path = Path(file_path)
    with open(file_path, "r", encoding="utf-8") as f:
        original = f.read()

    begin_pos = original.find(BEGIN_MARKER)
    if begin_pos != -1:
        end_pos = original.find(END_MARKER, begin_pos + len(BEGIN_MARKER))
        if end_pos != -1:
            # 替换标记之间的内容
            before = original[:begin_pos]
            after = original[end_pos + len(END_MARKER):]
            updated = before + new_content + after
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(updated)
            print(f"> 已更新文件 {file_path}（替换标记区间）")
            return

    # 没有完整标记对，则追加
    with open(file_path, "a", encoding="utf-8") as f:
        if original and not original.endswith("\n"):
            f.write("\n")
        f.write("\n" + new_content)
    print(f"> 已追加新内容到 {file_path}")


def get_next_temp_filename(output_dir):
    """在 output_dir 中生成递增的临时文件名，如 __Temp_Output_1.h, __Temp_Output_2.h ..."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    pattern = re.compile(rf"^{re.escape(TEMP_FILE_PREFIX)}(\d+){re.escape(TEMP_FILE_SUFFIX)}$")
    max_num = 0
    for f in output_dir.iterdir():
        if f.is_file():
            m = pattern.match(f.name)
            if m:
                num = int(m.group(1))
                if num > max_num:
                    max_num = num
    next_num = max_num + 1
    return output_dir / f"{TEMP_FILE_PREFIX}{next_num}{TEMP_FILE_SUFFIX}"


# ======================= 主程序 =======================
def main():
    parser = argparse.ArgumentParser(
        description="生成 C/C++ 预处理器宏，用于可变参数个数统计和遍历。",
        epilog="示例:\n"
               "  python MacroArgsNum.py                      # 生成默认配置，输出到 output/__Temp_Output_1.h\n"
               "  python MacroArgsNum.py --max 64             # 最大支持 64 个参数\n"
               "  python MacroArgsNum.py -i myheader.h        # 查找并修改 myheader.h\n"
               "  python MacroArgsNum.py -i myheader.h -o out.h  # 读取 myheader.h 并输出到 out.h\n"
               "  python MacroArgsNum.py --tools-dir MyTools   # 自定义向上查找的目录名\n"
               "  python MacroArgsNum.py --dry-run            # 仅打印生成的代码，不写文件",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--max", type=int, default=DEFAULT_MAX,
                        help=f"最大支持参数个数（默认 {DEFAULT_MAX}）")
    parser.add_argument("--foreach-prefix", default=DEFAULT_FOREACH_PREFIX,
                        help=f"FOREACH 宏前缀（默认 {DEFAULT_FOREACH_PREFIX}）")
    parser.add_argument("--nargs-prefix", default=DEFAULT_NARGS_PREFIX,
                        help=f"NARGS 宏前缀（默认 {DEFAULT_NARGS_PREFIX}）")
    parser.add_argument("--nargs-impl-prefix", default=DEFAULT_NARGS_IMPL_PREFIX,
                        help=f"NARGS_IMPL 宏前缀（默认 {DEFAULT_NARGS_IMPL_PREFIX}）")
    parser.add_argument("--tools-dir", default=DEFAULT_TOOLS_DIR_NAME,
                        help=f"向上查找的目录名，在其父目录下搜索输入文件（默认 {DEFAULT_TOOLS_DIR_NAME}）")
    parser.add_argument("--input", "-i", help="输入文件名。若仅为文件名，则按策略递归查找；否则视为路径")
    parser.add_argument("--output", "-o", help="输出文件（默认覆盖输入文件或自动生成临时文件）")
    parser.add_argument("--depth", type=int, default=DEFAULT_DEPTH,
                        help=f"递归搜索深度（默认 {DEFAULT_DEPTH}）")
    parser.add_argument("--dry-run", action="store_true",
                        help="仅打印生成的宏代码，不写入任何文件")

    args = parser.parse_args()

    if args.max < 1:
        print("❌ 错误:--max 必须至少为 1", file=sys.stderr)
        sys.exit(1)

    # 生成宏代码
    macros = generate_all_macros(
        args.foreach_prefix,
        args.nargs_prefix,
        args.nargs_impl_prefix,
        args.max
    )

    if args.dry_run:
        print(macros)
        return

    # 处理输入文件
    target_file = None
    if args.input:
        input_path = args.input
        # 判断是否为纯文件名（不含路径分隔符）
        if os.path.sep not in input_path and (os.path.altsep is None or os.path.altsep not in input_path):
            # 需要递归查找
            script_dir = Path(__file__).resolve().parent
            # 向上查找 tools-dir 目录，取其父目录作为搜索根
            search_root = find_tools_parent_dir(script_dir, args.tools_dir)
            print(f"> 在 {search_root} 下递归查找文件 '{input_path}'（深度 {args.depth}）")
            found = find_file_recursively(input_path, search_root, args.depth)
            if found:
                target_file = found
                print(f"> 找到文件:{target_file}")
            else:
                print(f"X 错误:在 {search_root} 中未找到文件 '{input_path}'（深度 {args.depth}）",
                      file=sys.stderr)
                sys.exit(1)
        else:
            # 给定的输入是一个路径（相对或绝对）
            p = Path(input_path)
            if p.exists():
                target_file = p.resolve()
            else:
                print(f"X 错误:输入文件 '{input_path}' 不存在", file=sys.stderr)
                sys.exit(1)

        # 确定输出文件
        output_file = args.output if args.output else target_file
        output_file = Path(output_file).resolve()

        if args.output and target_file != output_file:
            # 输入和输出不同:读取输入，处理内容，写入输出
            with open(target_file, "r", encoding="utf-8") as f:
                content = f.read()
            begin_pos = content.find(BEGIN_MARKER)
            if begin_pos != -1:
                end_pos = content.find(END_MARKER, begin_pos + len(BEGIN_MARKER))
                if end_pos != -1:
                    new_content = content[:begin_pos] + macros + content[end_pos + len(END_MARKER):]
                    with open(output_file, "w", encoding="utf-8") as f:
                        f.write(new_content)
                    print(f"> 已写入 {output_file}")
                else:
                    # 有开始无结束？追加到末尾
                    with open(output_file, "a", encoding="utf-8") as f:
                        if content and not content.endswith("\n"):
                            f.write("\n")
                        f.write("\n" + macros)
                    print(f"> 已追加到 {output_file}")
            else:
                # 无标记，直接追加
                with open(output_file, "a", encoding="utf-8") as f:
                    if content and not content.endswith("\n"):
                        f.write("\n")
                    f.write("\n" + macros)
                print(f"> 已追加到 {output_file}")
        else:
            # 原地修改（输入即输出）
            replace_or_append_content(target_file, macros)
    else:
        # 没有输入文件:自动生成临时文件
        script_dir = Path(__file__).resolve().parent
        output_dir = script_dir / OUTPUT_DIR_NAME
        temp_file = get_next_temp_filename(output_dir)
        with open(temp_file, "w", encoding="utf-8") as f:
            f.write(macros)
        print(f"✨ 已生成新文件:{temp_file}")


if __name__ == "__main__":
    main()

